on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:8u402-b06-jdk-jammy@sha256:a4f800ba32f5f9af86fca914a9c2cdd4d6f62f57a8b8146aad0b26b1efc65340
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - run: ./gradlew clean check
